class ConstantText {
  static String yourSkinJourneyStartHereText = 'Your Skin Journey Start Here!';
  static String emailText = 'Email';
  static String passwordText = 'Password';
  static String signInText = 'Sign in';
  static String forgotPasswordText = 'Forgot Password';
  static String signInWithGoogleText = 'Sign in with Google';
  static String signInWithFacebookText = 'Sign in with Facebook';
  static String dontHaveAnAccountText = 'Don’t have an account?';
  static String signUpText = 'Sign Up';
  static String usernameText = 'Username';
  static String numberText = 'Number';
  static String confirmPasswordText = 'Confirm Password';
  static String signUpWithGoogleText = 'Sign up with Google';
  static String signUpWithFacebookText = 'Sign up with Facebook';
  static String alreadyHaveAnAccountText = 'Already have an account?';
  static String apothogyText = 'apoth.o.gy';
  static String productsText = 'Products';
  static String drAndrewWeilForOriginText = 'Dr. Andrew Weil for Origin';
  static String rs1000Text = 'Rs.1000';
  static String nufaceByCarolCoreText = 'Nuface By CarolCore';
  static String rs2000Text = 'Rs.2000';
  static String allProductsText = 'All Products';
  static String freshSoyFaceCleanserText = "Fresh\nSoy Face Cleanser";
  static String rs1500Text = 'Rs.1500';
  static String doveText = 'Dove';
  static String profileText = 'Profile';
  static String editAccountText = 'Edit Account';
  static String user12345Text = 'User12345';
  static String userEmailText = 'user123@gmail.com';
  static String mySlideShowText = 'My Slide Show';
  static String applySkinFilterText = 'Apply Skin Filter';
  static String settingsText = 'Settings';
  static String logoutText = 'Logout';
  static String userInformationText = 'User Information';
  static String firstNameText = 'First Name';
  static String lastNameText = 'Last Name';
  static String genderText = 'Gender';
  static String phoneText = 'Phone';
  static String saveText = 'Save';
  static String selectFilterText = 'Select Filter';
  static String orderPreviewsText = 'Order Previews';
  static String oneKgText = '1 kg';
  static String oneUsdTText = '1 usdt';
  static String oneText = '1';
  static String oneDot49UsdTText = '1.49 usdt';
  static String shippingFeeText = 'Shipping Fee';
  static String zeroPoint59Text = '0.59 ';
  static String totalPaymentText = 'Total Payment';
  static String twoDot98Text = '2.98 ';
  static String pleaseAddYourShippingAddressText =
      'Please add your shipping address';
  static String yourPersonalDataWillBeUsedText =
      'Your personal data will be used only to process your order. For more details, please see ';
  static String privacyPolicyText = 'Privacy Policy';
  static String placeOrderText = 'Place Order';
  static String minusText = "-";
  static String plusText = '+';
  static String fiveDot0Text = '5.0';
  static String fragranceBottleDescriptionText =
      'A daydream of spring. Get lost in florals with notes of golden daffodil, airy honeysuckle and orange blossom. Flourish with matching Fragrance Mist.';
  static String fiftyMlText = '50ml';
  static String totalPriceText = 'Total Price';
  static String seventeenDollarText = r'$17.99';
  static String addToCartText = 'Add to cart';
// static String doveText = 'Dove';
// static String doveText = 'Dove';
// static String doveText = 'Dove';
// static String doveText = 'Dove';// static String doveText = 'Dove';
// static String doveText = 'Dove';
// static String doveText = 'Dove';

}
